base/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include

urlpatterns = [
    # ===============================
    # Authentication URLs
    # ===============================
    path('login/', views.loginUser, name='login'),
    path('logout/', views.logoutUser, name='logout'),
    path('change_password/', views.change_password, name='change_password'),

    # ===============================
    # User Management URLs
    # ===============================
    path('register_student/', views.register_student, name='register_student'),
    path('registered_students/', views.registered_students, name='registered_students'),
    path('delete_student/<int:student_id>/', views.delete_student, name='delete_student'),
    path('delete_staff/<int:staff_id>/', views.delete_staff, name='delete_staff'),
    path('change_role/<int:student_id>/', views.change_role, name='change_role'),
    path('edit_student/<int:student_id>/', views.edit_student, name='edit_student'),
    path('suspend_user/<int:user_id>/', views.suspend_user, name='suspend_user'),

    # ===============================
    # Dashboard URL
    # ===============================
    path('', views.dashboard, name='dashboard'),

    # ===============================
    # Course Management URLs
    # ===============================
    path('add_course/', views.add_course, name='add_course'),
    path('courses/', views.courses, name='courses'),
    path('delete_course/<int:course_id>/', views.delete_course, name='delete_course'),
    path('edit_course/<int:course_id>/', views.edit_course, name='edit_course'),

    # ===============================
    # Quiz Management URLs
    # ===============================
    path('add_quiz/', views.add_quiz, name='add_quiz'),
    path('quizzes/<int:course_id>/', views.quizzes, name='quizzes'),
    path('edit_quiz/<int:quiz_id>/', views.edit_quiz, name='edit_quiz'),
    path('delete_quiz/<int:quiz_id>/', views.delete_quiz, name='delete_quiz'),

    # ===============================
    # Submission Management URLs
    # ===============================
    path('submit_quiz/<int:quiz_id>/', views.submit_quiz, name='submit_quiz'),
    path('view_submissions/<int:course_id>/', views.view_submissions, name='view_submissions'),
    path('view_quiz_submissions/<int:quiz_id>/', views.view_quiz_submissions, name='view_quiz_submissions'),
    path('grade_submission/<int:submission_id>/', views.grade_submission, name='grade_submission'),
    path('remarks/<int:submission_id>/', views.remarks, name='remarks'),
    path('view_remarks/<int:submission_id>/', views.view_remarks, name='view_remarks'),

    # ===============================
    # Complaints Management URLs
    # ===============================
    path('submit_complaint/', views.submit_complaint, name='submit_complaint'),
    path('view_complaints/', views.view_complaints, name='view_complaints'),

    # ===============================
    # Rankings URL
    # ===============================
    path('view_overall_rank/', views.view_overall_rank, name='view_overall_rank'),

    # ===============================
    # Third Party URLs
    # ===============================
    path("ckeditor5/", include('django_ckeditor_5.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

studybud/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('base.urls')),
    path('admin/', admin.site.urls),
]

base/models.py
from django.db import models
from django.contrib.auth.models import User
import os

def student_directory_path(instance, filename):
    ext = filename.split('.')[-1]
    student_username = instance.student.username
    course_no = instance.course.course_no
    quiz_no = instance.quiz.quiz_no
    filename = f"{student_username}-{course_no}-{quiz_no}.{ext}"
    return os.path.join(f'{course_no}', filename)

class StudentProfile(models.Model):
    # Extending the user model with a student profile
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    gender = models.CharField(max_length=200)
    active_status = models.BooleanField(default=True)

    def __str__(self):
        return self.user.username

class Courses(models.Model):
    course_title = models.CharField(max_length=200)
    course_no = models.CharField(max_length=200, unique=True)

    def __str__(self):
        return self.course_title

class Quiz(models.Model):
    quiz_title = models.CharField(max_length=200)
    quiz_no = models.CharField(max_length=200, unique=True)
    description = models.TextField()
    help_file = models.FileField(upload_to='help_files/', null=True, blank=True)
    course = models.ForeignKey(Courses, on_delete=models.CASCADE,default=1)
    quiz_created_at = models.DateTimeField(auto_now_add=True)
    due_date = models.DateTimeField()

    def __str__(self):
        return self.quiz_title

class Submission(models.Model):
    student = models.ForeignKey(User, on_delete=models.CASCADE)
    course = models.ForeignKey(Courses, on_delete=models.CASCADE)
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    file = models.FileField(upload_to=student_directory_path)
    submitted_at = models.DateTimeField(auto_now_add=True)
    marks = models.IntegerField(null=True, blank=True)
    remarks = models.TextField(null=True, blank=True)
    
    def __str__(self):
        return f"{self.student.username} - {self.course.course_no} - {self.quiz.quiz_no}"

class StudentComplaints(models.Model):
    student = models.ForeignKey(User, on_delete=models.CASCADE)
    complaint = models.TextField(null=True, blank=True)
    submitted_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.student.username

base/forms.py
from django import forms
from django_ckeditor_5.widgets import CKEditor5Widget
from .models import Quiz, Submission, StudentComplaints


class QuizAddingForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['quiz_title'].required = True
        self.fields['quiz_no'].required = True
        self.fields['description'].required = True
        self.fields['due_date'].required = True
        self.fields['course'].required = True


        for field_name in self.fields:
            self.fields[field_name].help_text = ''

    class Meta:
        model = Quiz
        fields = "__all__"
        widgets = {
            "quiz_title": forms.TextInput(attrs={"class": "form-control"}),
            "quiz_no": forms.TextInput(attrs={"class": "form-control"}),
            "description": CKEditor5Widget(attrs={"class": "django_ckeditor_5", "config_name": "extends"}),
            "help_file": forms.FileInput(attrs={"class": "form-control"}),
            "due_date": forms.DateTimeInput(attrs={"class": "form-control", "type": "datetime-local"}),
            "course": forms.Select(attrs={"class": "form-control"}),
        }
        labels = {
            "quiz_title": "Quiz Title",
            "quiz_no": "Quiz No",
            "description": "Quiz Description",
            "help_file": "Help File",
            "due_date": "Due Date",
            "course": "Course",
        }

class RemarksForm(forms.ModelForm):
    class Meta:
        model = Submission
        fields = ["remarks"]
        widgets = {
            "remarks": CKEditor5Widget(attrs={"class": "django_ckeditor_5", "config_name": "extends"})
        }
        labels = {
            "remarks": "Remarks"
        }
    
class StudentComplaintsForm(forms.ModelForm):
    class Meta:
        model = StudentComplaints
        fields = ["complaint"]
        widgets = {
            "complaint": CKEditor5Widget(attrs={"class": "django_ckeditor_5", "config_name": "extends"})
        }
        labels = {
            "complaint": "Complaint"
        }

base/views.py
from django.shortcuts import render
from .forms import RemarksForm, QuizAddingForm, StudentComplaintsForm
from .models import Quiz, Submission, Courses, User, StudentProfile, StudentComplaints
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib import messages
from django.utils import timezone
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.contrib.auth.hashers import check_password
from django.shortcuts import render
from django.db.models import Sum, Count, Q
import httpagentparser

# ===============================
# Authentication Views
# ===============================

def loginUser(request):
    if request.user.is_authenticated:
        return redirect('dashboard')
    if request.method == 'POST':
        reg_no = request.POST.get('reg_no')
        password = request.POST.get('password')
        if not reg_no or not password:
            messages.error(request, 'Please enter both registration number and password')
            return redirect('login')
        user = authenticate(request, username=reg_no, password=password)
        if user is not None:
            if user.studentprofile.active_status:  
                login(request, user)
                return redirect('dashboard')
            else:
                messages.error(request, 'Account Suspended. Contact the Administrator.')
                return redirect('login')
        else:
            messages.error(request, 'Registration number or Password is incorrect')
    return render(request, 'base/login.html')

def logoutUser(request):
    logout(request)
    return redirect('login')

@login_required
def change_password(request):
    if request.method == 'POST':
        old_password = request.POST.get('old_password')
        new_password = request.POST.get('new_password')
        if not old_password or not new_password:
            messages.error(request, 'Please enter both old and new passwords')
            return redirect('change_password')
        confirm_password = request.POST.get('confirm_password')
        if not check_password(old_password, request.user.password):
            messages.error(request, 'Old password is incorrect')
            return redirect('change_password')
        if new_password != confirm_password:
            messages.error(request, 'New password and confirm password do not match')
            return redirect('change_password')
        user = request.user
        user.set_password(new_password)
        user.save()
        update_session_auth_hash(request, user)
        messages.success(request, 'Your password has been successfully updated!')
        return redirect('dashboard')
    return render(request, 'base/change_password.html')

# ===============================
# User Management Views
# ===============================

@staff_member_required(login_url='dashboard')
def register_student(request):
    if request.method == 'POST':
        reg_no = request.POST.get('reg_no')
        password = request.POST.get('password')
        first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')
        gender = request.POST.get('gender')
        if not reg_no or not password or not first_name or not last_name or not gender:
            messages.error(request, 'Please fill in all fields')
            return redirect('register_student')
        user = User.objects.create_user(username=reg_no, password=password, first_name=first_name, last_name=last_name)
        student_profile = StudentProfile.objects.create(user=user, gender=gender)
        messages.success(request, 'Student registered successfully')
        return redirect('dashboard')
    return render(request, 'base/register_student.html')

@staff_member_required(login_url='dashboard')
def registered_students(request):
    students = User.objects.filter(is_staff=False)
    staff = User.objects.filter(is_staff=True, is_superuser=False)
    super_users = User.objects.filter(is_superuser=True)
    return render(request, 'base/registered_students.html', {'students': students, 'staff': staff, 'super_users': super_users})

@staff_member_required(login_url='dashboard')
def edit_student(request, student_id):
    student = get_object_or_404(User, id=student_id)
    profile = get_object_or_404(StudentProfile, user=student)
    if request.method == 'POST':
        student.first_name = request.POST.get('first_name')
        student.last_name = request.POST.get('last_name')
        profile.gender = request.POST.get('gender')
        student.save()
        profile.save()
        messages.success(request, 'Student updated successfully')
        return redirect('registered_students')
    return render(request, 'base/edit_student.html', {'student': student, 'profile': profile})

@staff_member_required(login_url='dashboard')
def delete_student(request, student_id):
    student = get_object_or_404(User, id=student_id)
    if request.method == 'POST':
        student.delete()
        messages.success(request, 'Student deleted successfully')
        return redirect('registered_students')
    return render(request, 'base/delete_student.html', {'student': student})

@staff_member_required(login_url='dashboard')
def delete_staff(request, staff_id):
    staff = get_object_or_404(User, id=staff_id)
    if request.method == 'POST':
        staff.delete()
        messages.success(request, 'Staff deleted successfully')
        return redirect('registered_students')
    return render(request, 'base/delete_staff.html', {'staff': staff})

@staff_member_required(login_url='dashboard')
def change_role(request, student_id):
    student = get_object_or_404(User, id=student_id)
    if request.method == 'POST':
        role = request.POST.get('role')
        if not role:
            messages.error(request, 'Please select a role')
            return redirect('change_role', student_id)
        if role == 'student':
            student.is_staff = False
            student.is_superuser = False
        elif role == 'staff':
            student.is_staff = True
            student.is_superuser = False
        elif role == 'super_user':
            student.is_superuser = True
        student.save()
        messages.success(request, 'Role changed successfully')
        return redirect('registered_students')
    return render(request, 'base/change_role.html', {'student': student})

@staff_member_required(login_url='dashboard')
def suspend_user(request, user_id):
    user = get_object_or_404(User, id=user_id)
    user_profile = get_object_or_404(StudentProfile, user=user)
    if user_profile.active_status:
        user_profile.active_status = False
        messages.success(request, 'User suspended successfully')
    else:
        user_profile.active_status = True
        messages.success(request, 'User activated successfully')
    user_profile.save()
    return redirect('registered_students')

# ===============================
# Dashboard Views
# ===============================

@login_required(login_url='login')
def dashboard(request):
    courses = Courses.objects.all()
    quizzes = Quiz.objects.all()
    submissions = Submission.objects.filter(student=request.user)
    submission_counts = {course.id: submissions.filter(course=course).count() for course in courses}
    marks_sums = {
    course.id: submissions.filter(course=course, marks__isnull=False).aggregate(Sum('marks'))['marks__sum'] or 0
        for course in courses
    }
    user_agent = request.META.get('HTTP_USER_AGENT')
    user_ip = request.META.get('REMOTE_ADDR')
    device_info = httpagentparser.detect(user_agent)
    device_type = device_info.get("platform", {}).get("name", "Unknown Device")
    return render(request, 'base/dashboard.html', {'courses': courses, 'quizzes': quizzes, 'submissions': submissions, 'submission_counts': submission_counts, 'marks_sums': marks_sums, 'user_agent': user_agent, 'user_ip': user_ip, 'device_type': device_type})

# ===============================
# Course Management Views
# ===============================

@login_required(login_url='login')
def courses(request):
    courses = Courses.objects.all()
    return render(request, 'base/courses.html', {'courses': courses})

@staff_member_required(login_url='dashboard')
def add_course(request):
    if request.method == 'POST':
        course_title = request.POST.get('course_title')
        course_no = request.POST.get('course_no')
        if not course_title or not course_no:
            messages.error(request, 'Please fill in all fields')
            return redirect('add_course')
        Courses.objects.create(course_title=course_title, course_no=course_no)
        messages.success(request, 'Course added successfully')
        return redirect('courses')
    return render(request, 'base/add_course.html')

@staff_member_required(login_url='dashboard')
def edit_course(request, course_id):
    course = get_object_or_404(Courses, id=course_id)
    if request.method == 'POST':
        course.course_title = request.POST.get('course_title')
        course.course_no = request.POST.get('course_no')
        if not course.course_title or not course.course_no:
            messages.error(request, 'Please fill in all fields')
            return redirect('edit_course', course_id)
        course.save()
        messages.success(request, 'Course updated successfully')
        return redirect('courses')
    return render(request, 'base/edit_course.html', {'course': course})

@staff_member_required(login_url='dashboard')
def delete_course(request, course_id):
    course = get_object_or_404(Courses, id=course_id)
    if request.method == 'POST':
        course.delete()
        messages.success(request, 'Course deleted successfully')
        return redirect('courses')
    return render(request, 'base/delete_course.html', {'course': course})

base/templates/base/add_quiz.html
{% extends 'base/main.html' %}
{% load static %}
{% block title %}Add Quiz{% endblock %}
{% block content %}
{{ form.media }}
<div class="container">
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <div class="card">
                <div class="card-header">
                    <h4 style="text-align: center;"><strong>Add Quiz</strong></h4>
                </div>
                <div class="card-body">
                    <form method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% for field in form %}
                        <div class="form-group">
                            {{ field.label_tag }}
                            {{ field }}
                        </div>
                        {% endfor %}
                        <button type="submit" class="cstm-btn" style="width: 100%; border-radius: 5px;">Add Quiz</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% if messages %}
    <div id="popup-message-container">
        {% for message in messages %}
            <div class="popup-message {{ message.tags }}">
                {{ message }}
            </div>
        {% endfor %}
    </div>
{% endif %}
{% endblock %}

base/templates/base/change_role.html
{% extends 'base/main.html' %}
{% load static %}
{% block title %}Change Role{% endblock %}
{% block content %}
<div class="container">
    <h1>Change Role</h1>
    <form method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="role">Role:</label>
            <select class="form-control" id="role" name="role">
                <option value="student">Student</option>
                <option value="staff">Staff</option>
                <option value="super_user">Super User</option>
            </select>
        </div>
        <button type="submit" class="sub-label" style="padding: 0px; text-align: center; width: 120px; margin-left: 15px; margin-top: 5px;"><i class="fa-solid fa-user-shield"></i> Change Role</button>
    </form>
</div>
{% if messages %}
    <div id="popup-message-container">
        {% for message in messages %}
            <div class="popup-message {{ message.tags }}">
                {{ message }}
            </div>
        {% endfor %}
    </div>
{% endif %}
{% endblock %}

base/templates/base/courses.html
{% extends 'base/main.html' %}
{% load static %}
{% block title %} Courses {% endblock %}
{% block content %}
<style>
    a {
        text-decoration: none;
        color: black;
    }

    a:hover {
        color: black;
        text-decoration: none;
    }
</style>
<div class="quiz-main-container" style="height: 88vh;">
    <div id="quiz-container" class="quiz-main-container-box">
        <h3 class="quiz-title-2"><strong>Courses</strong></h3>
        <div class="table-responsive">
            <table id="course-table" style="vertical-align: middle; min-width: 100%;"
                class="table table-hover table-bordered">
            <thead>
                <tr>
                    <th width="4%"><strong>Course ID</strong></th>
                    <th width="12%"><strong>Course Title</strong></th>
                    {% if user.is_staff %}
                    <th width="2%" style="text-align: center;"><strong>Action</strong></th>
                    {% endif %}
                </tr>
            </thead>
            <tbody>
                {% for course in courses %}
                <tr>
                    <td class="m">{{course.course_no}}</td>
                    <td class="m"><a href="{% url 'quizzes' course.id %}">{{course.course_title}}</a></td>
                    {% if user.is_staff %}
                    <td class="m" style="display: flex; justify-content: center; align-items: center; gap: 10px;">
                        <a href="{% url 'delete_course' course.id %}">
                            <button class="sub-danger-label" style="padding: 0px; width: 100px; margin-top: 5px;">
                                <i class="fa-solid fa-trash-can"></i> Delete
                            </button>
                        </a>
                        <a href="{% url 'edit_course' course.id %}">
                            <button class="sub-label" style="padding: 0px; width: 100px; margin-top: 5px;">
                                <i class="fa-solid fa-user-edit"></i> Edit
                            </button>
                        </a>
                        <a href="{% url 'view_submissions' course.id %}">
                            <button class="sub-label" style="padding: 0px; width: 100px; margin-top: 5px;">
                                <i class="fa fa-eye"></i> View
                            </button>
                        </a>
                    </td>
                    {% endif %}
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% if messages %}
    <div id="popup-message-container">
        {% for message in messages %}
            <div class="popup-message {{ message.tags }}">
                {{ message }}
            </div>
        {% endfor %}
    </div>
{% endif %}
{% endblock %}

base/templates/base/dashboard.html
{% extends 'base/main.html' %}
{% load static %}
{% load custom_tags %}
{% block title %}Dashboard{% endblock %}
{% block content %}
<style>
    body {
        font-size: small;
    }
</style>
<div class="main-container">
    <div class="dashboard-title-container">
        <h3><strong>DASHBOARD</strong></h3>
    </div>
    <div class="main-container-box" id="box1">
        {% if user.studentprofile.gender == 'Female' %}
        <img src="{% static 'images/fmale.png' %}" alt="female" class="profile-pic">
        {% else %}
        <img src="{% static 'images/male.png' %}" alt="male" class="profile-pic">
        {% endif %}
        <h4 class="profile-name"><strong>{{user.first_name | upper}} {{user.last_name | upper}}</strong></h4>
        <h4 class="profile-id"><strong>{{user.username | upper}}</strong></h4>
    </div>
    <div class="main-container-box" id="box2">
        <div class="table-responsive">
            <table class="table table-bordered md">
                <thead>
                <tr>
                    <th rowspan="2" width="15%">Course ID</th>
                    <th rowspan="2" width="40%">Title</th>
                    <th rowspan="2" width="15%">Submissions</th>
                    <th rowspan="2" width="15%">Quiz Submitted</th>
                    <th rowspan="2" width="15%">Marks</th>
                    <th rowspan="2" width="15%">Total Quizzes</th>
                </tr>
            </thead>
            <tbody>
                {% for course in courses %}
                <tr>
                    <td>{{course.course_no}}</td>
                    <td>{{course.course_title}}</td>
                    <td><a href="{% url 'quizzes' course.id %}"><input type="button" name="view" value="View Quizzes"
                        class="cstm-dead-btn view-deadline-btn"></a>
                    </td>
                    <td class="text-center">
                        <span class="sub-label">{{ submission_counts|get_item:course.id|default:0 }} Submitted</span>
                    </td>
                    <td class="text-center">
                        <span class="sub-label">{{ marks_sums|get_item:course.id|default:0 }} Marks</span>
                    </td>
                    <td class="text-center">
                        {% if course.quiz_set.count > 1 %}
                        <span class="total-label" id="quizzes-label">{{course.quiz_set.count}} Quizzes</span><br><br>
                        {% else %}
                        <span class="total-label" id="quizzes-label">{{course.quiz_set.count}} Quiz</span><br><br>
                        {% endif %}
                    </td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% if messages %}
    <div id="popup-message-container">
        {% for message in messages %}
            <div class="popup-message {{ message.tags }}">
                {{ message }}
            </div>
        {% endfor %}
    </div>
{% endif %}
{% endblock %}

base/templates/base/delete_quiz.html
{% extends 'base/main.html' %}
{% load static %}
{% block title %}Delete Quiz{% endblock %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <div class="card">
                <div class="card-header">
                    <h4 style="text-align: center;"><strong>Delete Quiz</strong></h4>
                </div>
                <div class="card-body">
                    <form method="POST">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="quiz_id">Quiz ID</label>
                            <input type="text" class="form-control" id="quiz_id" name="quiz_id" value="{{ quiz.id }}" readonly>
                        </div>
                        <div class="form-group">
                            <label for="quiz_title">Quiz Title</label>
                            <input type="text" class="form-control" id="quiz_title" name="quiz_title" value="{{ quiz.quiz_title }}" readonly>
                        </div>
                        <div class="form-group">
                            <label for="quiz_no">Quiz No</label>
                            <input type="text" class="form-control" id="quiz_no" name="quiz_no" value="{{ quiz.quiz_no }}" readonly>
                        </div>
                        <div class="form-group">
                            <label for="due_date">Deadline</label>
                            <input type="datetime-local" class="form-control" id="due_date" name="due_date" value="{{ quiz.due_date }}" readonly>
                        </div>
                        <button type="submit" class="cstm-btn" style="background-color: #a11510; color: white; width: 100%; border-radius: 5px;"><i class="fa-solid fa-trash-can"></i> Delete Quiz</button>
                        <a href="{% url 'quizzes' quiz.course.id %}"><button type="button" class="cstm-btn" style="margin-top: 10px; background-color: #119247; color: white; width: 100%; border-radius: 5px;"><i class="fa-solid fa-xmark"></i> Cancel</button></a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% if messages %}
    <div id="popup-message-container">
        {% for message in messages %}
            <div class="popup-message {{ message.tags }}">
                {{ message }}
            </div>
        {% endfor %}
    </div>
{% endif %}
{% endblock %}

base/templates/base/edit_quiz.html
{% extends 'base/main.html' %}
{% load static %}
{% block title %}Edit Quiz{% endblock %}
{% block content %}
{{ form.media }}
<div class="container">
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <div class="card">
                <div class="card-header">
                    <h4 style="text-align: center;"><strong>Edit Quiz</strong></h4>
                </div>
                <div class="card-body">
                    <form method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% for field in form %}
                        <div class="form-group">
                            {{ field.label_tag }}
                            {{ field }}
                        </div>
                        {% endfor %}
                        <button type="submit" class="cstm-btn" style="width: 100%; border-radius: 5px;">Update Quiz</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% if messages %}
    <div id="popup-message-container">
        {% for message in messages %}
            <div class="popup-message {{ message.tags }}">
                {{ message }}
            </div>
        {% endfor %}
    </div>
{% endif %}
{% endblock %}

base/templates/base/login.html
{% extends 'base/main.html' %}
{% load static %}
{% block title %}Login{% endblock %}
{% block content %}
<form action="" method="post">
    {% csrf_token %}
    <div class="container-box">
        <div class="box">
            <div class="cstm-logo-container">
                <img src="{% static 'images/lms_logo.png' %}" class="cstm-logo">
                {% if messages %}
                {% for message in messages %}
                <p class="red_alert">{{ message }}</p>
                {% endfor %}
                {% endif %}
            </div>
            <div class="input-icon">
                <input type="text" name="reg_no" placeholder="Registration Number" class="input-field">
                <img src="{% static 'images/lock.png' %}" class="icon">
            </div>

            <div class="input-icon">
                <input type="password" name="password" placeholder="Password" id="password_field" class="input-field">
                <img src="{% static 'images/hide.png' %}" class="icon" id="hide_icon">
            </div>
            <button class="cstm-btn">Login</button>
            <p class="footer-text">For any issues contact &nbsp;<a id="footer-link" href="https://zaidkx7.github.io/"
                    target="_blank">&nbsp;<strong>Muhammad Zaid</strong></a></p>
        </div>
    </div>
</form>
<script>
    let hide = document.querySelector('#hide_icon');
    hide.addEventListener('click', () => {
        let password = document.querySelector('#password_field');
        if (password.type === 'password') {
            password.type = 'text';
            hide.src = "{% static 'images/hide.png' %}";
        } else {
            password.type = 'password';
            hide.src = "{% static 'images/show.png' %}";
        }
    });
</script>
{% endblock %}